import numpy as np
import pandas as pd
import sys

def calculate_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Transforms raw asset, benchmark, VIX prices, and fundamental inputs into 
    structured mathematical features. Infuses advanced velocity, direction, 
    and volatility squeeze mechanics chronologically.
    """
    # Create a copy to protect original data integrity and guarantee time order
    feat_df = df.copy().sort_index()
    
    print("Beginning mathematical feature engineering extraction...")
    
    # ----------------------------------------------------
    # 1. Base Log Returns (Ensuring stationarity)
    # ----------------------------------------------------
    feat_df['asset_ret'] = np.log(feat_df['asset_close'] / feat_df['asset_close'].shift(1))
    feat_df['spy_ret'] = np.log(feat_df['spy_close'] / feat_df['spy_close'].shift(1))
    
    # ----------------------------------------------------
    # 2. CAPM Alpha, Beta, & Residual (Idiosyncratic News Signal)
    # ----------------------------------------------------
    window = 60  # 60 trading days (~3 calendar months) to capture structural regimes
    
    rolling_cov = feat_df['asset_ret'].rolling(window=window).cov(feat_df['spy_ret'])
    rolling_market_var = feat_df['spy_ret'].rolling(window=window).var()
    
    feat_df['capm_beta'] = rolling_cov / rolling_market_var
    
    rolling_asset_mean = feat_df['asset_ret'].rolling(window=window).mean()
    rolling_spy_mean = feat_df['spy_ret'].rolling(window=window).mean()
    feat_df['capm_alpha'] = rolling_asset_mean - (feat_df['capm_beta'] * rolling_spy_mean)
    
    feat_df['residual_return'] = feat_df['asset_ret'] - (feat_df['capm_alpha'] + feat_df['capm_beta'] * feat_df['spy_ret'])
    
    # ----------------------------------------------------
    # 3. Technical Horizons & Structural Crossovers
    # ----------------------------------------------------
    feat_df['trend_20d'] = feat_df['asset_ret'].rolling(20).sum()
    feat_df['trend_60d'] = feat_df['asset_ret'].rolling(60).sum()
    
    # Trend Structural Crossovers
    feat_df['feature_trend_bullish_cross'] = (feat_df['trend_20d'] > feat_df['trend_60d']).astype(int)
    feat_df['feature_trend_bearish_cross'] = (feat_df['trend_20d'] < feat_df['trend_60d']).astype(int)
    
    # Momentum: Standard 14-day Relative Strength Index (RSI)
    delta = feat_df['asset_close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / (loss + 1e-9)
    feat_df['momentum_rsi'] = 100 - (100 / (1 + rs))
    
    # RSI Logic Boundaries
    feat_df['feature_rsi_oversold'] = (feat_df['momentum_rsi'] < 30).astype(int)
    feat_df['feature_rsi_overbought'] = (feat_df['momentum_rsi'] > 70).astype(int)
    
    # Volatility & Volume Profiles
    feat_df['volatility_20d'] = feat_df['asset_ret'].rolling(window=20).std()
    feat_df['volume_ratio'] = feat_df['asset_volume'] / feat_df['asset_volume'].rolling(window=20).mean()
    
    # ----------------------------------------------------
    # 4. VOLATILITY COMPRESSION & ENERGY METRICS (New)
    # ----------------------------------------------------
    # Bollinger Band Width (Squeeze vs. Overextension)
    bb_sma = feat_df['asset_close'].rolling(window=20).mean()
    bb_std = feat_df['asset_close'].rolling(window=20).std()
    feat_df['feature_bb_width'] = (4 * bb_std) / bb_sma
    
    # Volatility Ratio tracking structural breakout expansions
    feat_df['feature_volatility_ratio'] = feat_df['asset_ret'].rolling(window=14).std()

    # ----------------------------------------------------
    # 5. FIRST DERIVATIVES & SYSTEM SPEED (Velocities)
    # ----------------------------------------------------
    # Trend Velocities (Is the speed expanding or decaying?)
    feat_df['feature_trend_20d_velocity'] = feat_df['trend_20d'].diff(5)
    feat_df['feature_trend_60d_velocity'] = feat_df['trend_60d'].diff(5)
    
    # Categorical Velocities (Current Market Slope Direction)
    feat_df['feature_trend_20d_dir'] = (feat_df['feature_trend_20d_velocity'] > 0).astype(int)
    feat_df['feature_trend_60d_dir'] = (feat_df['feature_trend_60d_velocity'] > 0).astype(int)
    
    # Core Valuation Shift Velocities (Calculated over the 5-day delta)
    features_to_differentiate = ['momentum_rsi', 'ratio_pe', 'ratio_pb', 'ratio_dcf_value']
    for col in features_to_differentiate:
        if col in feat_df.columns:
            feat_df[f'feature_{col}_velocity_5d'] = feat_df[col].diff(5)

    # ----------------------------------------------------
    # 6. Macro Risk Metrics
    # ----------------------------------------------------
    feat_df['macro_vix'] = feat_df['vix_close']
    feat_df['vix_change_5d'] = feat_df['vix_close'].pct_change(periods=5)
    feat_df['feature_value_disconnect'] = feat_df['ratio_pe'] * feat_df['ratio_dcf_value']
    # Clean up NaNs generated by rolling windows at the absolute beginning of history
    feat_df = feat_df.dropna()
    
    print(f"Feature engineering complete. Total feature columns generated: {feat_df.shape[1] - df.shape[1]}")
    return feat_df

if __name__ == "__main__":
    sys.path.append('/content/ml-equity-classifier/src/')
    from data_fetcher import fetch_market_data
    raw_data = fetch_market_data("AAPL", "2016-01-01", "2026-01-01")
    
    if not raw_data.empty:
        processed_data = calculate_features(raw_data)
        print("\nProcessed Features preview (Tail):")
        print(processed_data[['capm_beta', 'feature_bb_width', 'feature_trend_20d_velocity', 'macro_vix']].tail())